---
version: 2

updates:
  - directory: /
    package-ecosystem: npm
    schedule:
      interval: daily
    ignore:
      - dependency-name: '@types/node'
        versions: ['>=11.0.0-0']
    versioning-strategy: increase
