language: node_js
node_js:
- '8'
cache: npm

env:
  global:
    secure: KhjNDRskbypSD9KnbcL8inGdtDiHCxJR5NQjtnebNu4PyCvWjCIG1pc4437ttIYmv4gw52x1V0SR5PjFvUKcujwykw5U8Jvi7b2LFpe648QAVNvbNUSzTpATzWy/fqsUtqxLYz0sgCjT2m+uX8uPiISSc8ScR9K0F68WW3WNOa0+smuzAajiYJ5vQIMUwLKZcTNuxQ8jlZMEh2dLlkaw5vxcuLT2emZOlGDxzJMyOksoPfteW+87RFDDR5Pwkzk3fo0dUaiXn5KuanX/dmGPJ4RljZCNZ8Nc7WqvN2+dGOLqBxgan3AbN3eHoAj1pRcVCUisvFJ0sJ+hEpry/JO38hvhLr8UTHBtT7DqHOmdSMHbrqS+fUD7SO1MfWQ9QdbpKWoowycceOnP1KrLqNj+CIrEPKqjrMSkfghBG6YD4FP19MR7Zwr36hqjT/qk7NU45eh2no6Mw+kAAjT8gKL7ddboJ3BR729oDVhFcQVjch+C5XpRb+mchjMtSeAw4CL1LAkrwFxu7OixSCYOIVIKRzPttH/odc6KKCZt0TxwMqsjDCJVsRXfCBQJqJR7JG+L4nelATrW0oC0KUcS1UhUUagNJ1oBWDpCjzedfDZZN1HE3Cx3o9Sy3xR7iWovKkmq0lgPKm9Ssx9UBXaRw5QvRCzISrvPUAX+4duFeiCLZvU=

before_install:
- npm install -g npm@^6.9.0
- npm install -g greenkeeper-lockfile
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 -o /tmp/cc-test-reporter
- chmod +x /tmp/cc-test-reporter

before_script:
- greenkeeper-lockfile-update
- /tmp/cc-test-reporter before-build
script:
- npm run build
- npm test
after_script:
- find coverage -name lcov.info | xargs -n 1 -I '{}' /tmp/cc-test-reporter format-coverage --input-type lcov -o '{}'.cc '{}'
- /tmp/cc-test-reporter sum-coverage --parts $(find coverage -name lcov.info.cc | wc -l) $(find coverage -name lcov.info.cc)
- /tmp/cc-test-reporter upload-coverage
- /tmp/cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
- greenkeeper-lockfile-upload

deploy:
  skip_cleanup: true
  provider: npm
  email: romain.muller@telecomnancy.net
  api_key:
    secure: XKj295k/Ofjuql+W4B02JuSGL8ICNhYz8I3qQV0y24Xp+CKsnUjjcAdPysgMjtZFpvFqN37UifTjo7mLOGryzijg7vazj8eBAnJrTsT6MSUcy+YG3ulMHBMHLR7rZsY1xUvVpixNvLlYNcNfbJf0ET0qNrOc8eyy4XLO2kcEGwuZcjQsg3tkxgVXCR41mKiC7QWV5StdFgSmC50WK2x03wOAKWA3PAI3kqTz+a6QUErVHMDLdSnbQ2vNc4OYl4lJejw8ulctCRBvS+vtOKYHrCkmKdGXqo/OydJRlpJM0GawAyvj8E6cmL+s8JiOHQ8stf5cQbBgFOA1ZvD/x2wUS2FJR5EoPX6z4R6XUxZKu3NsA+x9dxDdENo/W9hHRtDY5jQ/GwZ+rvq7zu+jnZWhtqsWIRvFGaB++oQmJlPJyZSp0TzbioXzoTU+hVRoakO+mnpdX0JhbaZeyXxR4YWAAAPa4k8iRj5RyqabvO7NBI87gBOH4CgqynqEPpDGlYzHRRxbROkmm0rmQTgNsC/8N3qVkeHdRmFDgpCawbTuh/+CKOeWaqDrSuS2TNnxgQJYF0JjT4zaCr7QVO4Kh+87y64VilMJJuZfoI2yhISPmZkE/1EOWdbJR2oa46oyZ2dT9wOZriYzrBZAz/k5Rtog0hguk4ETqRIiEk8iTC7jLis=
  on:
    tags: true
    repo: RomainMuller/pko
