---
version: 1

update_configs:
  - package_manager: javascript
    directory: /
    update_schedule: live
    version_requirement_updates: increase_versions
    allowed_updates:
      - match:
          update_type: all
    automerged_updates:
      - match:
          dependency_name: '@types/node'
          update_type: 'semver:minor'
      - match:
          dependency_type: all
          update_type: all
