name: Pull Requests

on:
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
      - uses: actions/checkout@master
      - name: Use Node ${{matrix.node-version}}
        uses: actions/setup-node@master
        with:
          version: ${{matrix.node-version}}
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
